# Generated by Django 6.0.6 on 2026-06-19 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='靶纸名称')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='靶纸图片')),
                ('ring_count', models.SmallIntegerField(default=10, verbose_name='环数')),
                ('ring_definitions', models.JSONField(default=list, help_text='每环的半径定义(mm)', verbose_name='环定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '靶纸模板',
                'verbose_name_plural': '靶纸模板',
                'db_table': 'target_templates',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_meters', models.FloatField(default=10.0, verbose_name='距离(米)')),
                ('calibration', models.JSONField(default=dict, verbose_name='标定信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='targets.targettemplate', verbose_name='靶纸模板')),
            ],
            options={
                'verbose_name': '靶纸',
                'verbose_name_plural': '靶纸',
                'db_table': 'targets',
            },
        ),
    ]
