# Generated by Django 6.0.6 on 2026-06-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targettemplate',
            name='category',
            field=models.CharField(choices=[('standard', '标准环靶'), ('silhouette', '人形靶'), ('ipsc', 'IPSC靶'), ('steel', '钢靶'), ('custom', '自定义')], default='standard', max_length=20, verbose_name='靶纸类型'),
        ),
        migrations.AddField(
            model_name='targettemplate',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='targettemplate',
            name='height_mm',
            field=models.FloatField(default=170.0, verbose_name='靶纸高度(mm)'),
        ),
        migrations.AddField(
            model_name='targettemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='targets/', verbose_name='靶纸图片'),
        ),
        migrations.AddField(
            model_name='targettemplate',
            name='width_mm',
            field=models.FloatField(default=170.0, verbose_name='靶纸宽度(mm)'),
        ),
        migrations.AlterField(
            model_name='targettemplate',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='外部图片链接（备用）'),
        ),
        migrations.AlterField(
            model_name='targettemplate',
            name='ring_definitions',
            field=models.JSONField(default=list, help_text='每环的半径定义(mm)，例如 [{"ring":10,"radius_mm":50},...]', verbose_name='环定义'),
        ),
    ]
