# Generated by Django 6.0.6 on 2026-06-19 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Drill 名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('cartridge_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Cartridge 类型')),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', '入门'), ('intermediate', '中级'), ('advanced', '高级')], default='', max_length=20, verbose_name='难度')),
                ('default_params', models.JSONField(default=dict, verbose_name='默认参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drill 模板',
                'verbose_name_plural': 'Drill 模板',
                'db_table': 'drill_templates',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_meters', models.FloatField(blank=True, null=True, verbose_name='距离(米)')),
                ('status', models.CharField(choices=[('created', '已创建'), ('in_progress', '训练中'), ('paused', '已暂停'), ('completed', '已完成'), ('aborted', '已中止')], default='created', max_length=20, verbose_name='状态')),
                ('total_shots', models.PositiveIntegerField(default=0, verbose_name='总枪数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='持续时长(秒)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.device', verbose_name='设备')),
                ('drill_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.drilltemplate', verbose_name='Drill 模板')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='targets.target', verbose_name='靶纸')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '训练 Session',
                'verbose_name_plural': '训练 Session',
                'db_table': 'training_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_ring', models.FloatField(blank=True, null=True, verbose_name='平均环数')),
                ('group_radius_mm', models.FloatField(blank=True, null=True, verbose_name='散布半径(mm)')),
                ('center_offset_mm', models.FloatField(blank=True, null=True, verbose_name='中心偏移(mm)')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='总分')),
                ('scatter_data', models.JSONField(default=list, verbose_name='靶面散点数据')),
                ('direction_data', models.JSONField(default=list, verbose_name='方向图数据')),
                ('score_curve', models.JSONField(default=list, verbose_name='分数曲线')),
                ('motion_data', models.JSONField(default=list, verbose_name='动作图数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '训练结果',
                'verbose_name_plural': '训练结果',
                'db_table': 'training_results',
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shot_number', models.PositiveIntegerField(verbose_name='枪序号')),
                ('imu_data', models.JSONField(default=dict, help_text='加速度计和陀螺仪时间序列，窗口-200ms~+100ms', verbose_name='IMU 数据')),
                ('trigger_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='击发时刻')),
                ('hit_x', models.FloatField(blank=True, null=True, verbose_name='命中 X 坐标')),
                ('hit_y', models.FloatField(blank=True, null=True, verbose_name='命中 Y 坐标')),
                ('hit_ring', models.FloatField(blank=True, null=True, verbose_name='命中环数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '单枪数据',
                'verbose_name_plural': '单枪数据',
                'db_table': 'shots',
                'ordering': ['shot_number'],
                'unique_together': {('session', 'shot_number')},
            },
        ),
    ]
