# Generated by Django 6.0.6 on 2026-06-19 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_sn', models.CharField(max_length=64, unique=True, verbose_name='设备序列号')),
                ('device_name', models.CharField(blank=True, default='', max_length=128, verbose_name='设备名称')),
                ('firmware_version', models.CharField(blank=True, default='', max_length=32, verbose_name='固件版本')),
                ('battery_level', models.SmallIntegerField(blank=True, null=True, verbose_name='电量百分比')),
                ('is_bound', models.BooleanField(default=True, verbose_name='是否绑定')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前是否激活')),
                ('mac_address', models.CharField(blank=True, default='', max_length=32, verbose_name='MAC地址')),
                ('last_online_at', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.SmallIntegerField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=32)),
                ('signal_strength', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='devices.device', verbose_name='设备')),
            ],
            options={
                'db_table': 'device_status_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
