# Generated by Django 6.0.6 on 2026-06-19 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='课程标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='课程描述')),
                ('cover_image', models.URLField(blank=True, default='', verbose_name='封面图')),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', '入门'), ('intermediate', '中级'), ('advanced', '高级')], default='', max_length=20, verbose_name='难度')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='章节标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='章节内容')),
                ('video_url', models.URLField(blank=True, default='', verbose_name='视频链接')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'db_table': 'course_sections',
                'ordering': ['sort_order'],
            },
        ),
    ]
