# Generated by Django 6.0.6 on 2026-06-19 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_model', models.CharField(max_length=64, verbose_name='设备型号')),
                ('version', models.CharField(max_length=32, verbose_name='版本号')),
                ('release_notes', models.TextField(blank=True, default='', verbose_name='更新说明')),
                ('file_url', models.URLField(verbose_name='固件文件地址')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('checksum', models.CharField(max_length=128, verbose_name='校验和')),
                ('is_force_update', models.BooleanField(default=False, verbose_name='是否强制升级')),
                ('min_battery_required', models.SmallIntegerField(default=20, verbose_name='最低电量要求')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('revoked', '已撤销')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '固件',
                'verbose_name_plural': '固件',
                'db_table': 'firmwares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmwareUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_version', models.CharField(max_length=32, verbose_name='升级前版本')),
                ('to_version', models.CharField(max_length=32, verbose_name='升级后版本')),
                ('status', models.CharField(choices=[('pending', '待升级'), ('downloading', '下载中'), ('upgrading', '升级中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='devices.device', verbose_name='设备')),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_logs', to='ota.firmware', verbose_name='固件')),
            ],
            options={
                'verbose_name': '固件升级记录',
                'verbose_name_plural': '固件升级记录',
                'db_table': 'firmware_update_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
