# Generated by Django 6.0.6 on 2026-06-19 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_ring', models.FloatField(verbose_name='平均环数')),
                ('group_radius', models.FloatField(verbose_name='散布半径')),
                ('center_offset', models.FloatField(verbose_name='中心偏移')),
                ('ring_score', models.FloatField(verbose_name='环数得分')),
                ('group_score', models.FloatField(verbose_name='散布得分')),
                ('offset_score', models.FloatField(verbose_name='偏移得分')),
                ('total_score', models.FloatField(verbose_name='准度总分(Accuracy Score)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_score', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '准度评分',
                'verbose_name_plural': '准度评分',
                'db_table': 'accuracy_scores',
            },
        ),
        migrations.CreateModel(
            name='IssueDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.JSONField(default=list, help_text='每个问题包含 label/severity/description', verbose_name='问题列表')),
                ('accuracy_limitations', models.JSONField(default=list, verbose_name='准度限制因素')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '问题诊断',
                'verbose_name_plural': '问题诊断',
                'db_table': 'issue_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='MotionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_control', models.FloatField(verbose_name='扳机控制分')),
                ('stability', models.FloatField(verbose_name='稳定性分')),
                ('follow_through', models.FloatField(verbose_name='Follow-through 分')),
                ('consistency', models.FloatField(verbose_name='一致性分')),
                ('total_score', models.FloatField(verbose_name='动作总分(Motion Score)')),
                ('details', models.JSONField(default=dict, verbose_name='分项明细')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motion_score', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '动作评分',
                'verbose_name_plural': '动作评分',
                'db_table': 'motion_scores',
            },
        ),
        migrations.CreateModel(
            name='NeutralPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_too_long_count', models.PositiveIntegerField(default=0)),
                ('timeout_no_shot_count', models.PositiveIntegerField(default=0)),
                ('abort_count', models.PositiveIntegerField(default=0)),
                ('safety_violation_count', models.PositiveIntegerField(default=0)),
                ('mode_rule_violation_count', models.PositiveIntegerField(default=0)),
                ('total_penalty', models.FloatField(default=0, verbose_name='总罚分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neutral_penalty', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '中性罚分',
                'verbose_name_plural': '中性罚分',
                'db_table': 'neutral_penalties',
            },
        ),
        migrations.CreateModel(
            name='OverallScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_weight', models.FloatField(default=0.5, verbose_name='动作权重')),
                ('accuracy_weight', models.FloatField(default=0.5, verbose_name='准度权重')),
                ('total_score', models.FloatField(verbose_name='综合总分(Overall Score)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_score', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '综合评分',
                'verbose_name_plural': '综合评分',
                'db_table': 'overall_scores',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, help_text='每条包含 issue/drill/success_criteria', verbose_name='建议列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '训练建议',
                'verbose_name_plural': '训练建议',
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='SkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('L1', 'Beginner'), ('L2', 'Novice'), ('L3', 'Intermediate'), ('L4', 'Advanced'), ('L5', 'Expert')], default='L1', max_length=20, verbose_name='当前等级')),
                ('ema_motion_score', models.FloatField(default=0, verbose_name='EMA 动作分')),
                ('ema_accuracy_score', models.FloatField(default=0, verbose_name='EMA 准度分')),
                ('total_sessions_analyzed', models.PositiveIntegerField(default=0, verbose_name='已分析训练次数')),
                ('trend_data', models.JSONField(default=list, verbose_name='趋势数据')),
                ('accuracy_mastery_level', models.CharField(blank=True, default='', max_length=20, verbose_name='准度精通等级')),
                ('accuracy_profile', models.JSONField(default=dict, verbose_name='准度画像')),
                ('next_accuracy_focus', models.CharField(blank=True, default='', max_length=128, verbose_name='下一步准度重点')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_rating', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '水平评估',
                'verbose_name_plural': '水平评估',
                'db_table': 'skill_ratings',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('7d', '7天'), ('14d', '14天'), ('30d', '30天')], max_length=10, verbose_name='计划类型')),
                ('daily_plans', models.JSONField(default=list, verbose_name='每日训练清单')),
                ('completion_rate', models.FloatField(default=0, verbose_name='完成度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否当前计划')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '训练计划',
                'verbose_name_plural': '训练计划',
                'db_table': 'training_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCoachingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('pre_trigger_jerk_risk', 'Pre-trigger jerk risk'), ('hold_too_long', 'Hold too long'), ('follow_through_too_short', 'Follow-through too short'), ('tempo_too_fast', 'Tempo too fast'), ('good_shot', 'Good shot reinforcement')], max_length=40, verbose_name='事件类型')),
                ('priority', models.CharField(choices=[('safety', 'Safety'), ('process', 'Process'), ('correction', 'Correction'), ('encouragement', 'Encouragement')], max_length=20, verbose_name='优先级')),
                ('message', models.TextField(verbose_name='语音消息文本')),
                ('is_played', models.BooleanField(default=False, verbose_name='是否已播放')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_events', to='training.trainingsession', verbose_name='所属 Session')),
            ],
            options={
                'verbose_name': '语音指导事件',
                'verbose_name_plural': '语音指导事件',
                'db_table': 'voice_coaching_events',
                'ordering': ['created_at'],
            },
        ),
    ]
